jobs:
  include:
  - stage: test backend
    language: python
    python:
    - 2.7.15
    install:
    - pip install -r requirements.txt
    script:
    - bash ./bin/runTests.sh --python
  - stage: test frontend
    language: node_js
    node_js:
    - 8.12.0
    install:
    - "(cd frontend && npm ci)"
    script:
    - bash ./bin/runTests.sh --nodejs-coverage
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: FZLwOljM2uryfZHKUyJdUUyTPuoP8WDGnjXof3uiyYZTiQX8LLW8FxW3dnxhv8Zf60hHWpPy4HHRNJkgzWx9BdKq+D71kFQTUfTun/C29B2yJXMOcOaUs0MMhDjk1r07q5ECO8TwRlSYoWNYiQunwWXKdIOk+zffd/zjJAlShKbgniuqjX0Ml4wleQTVtO9j3m1LxkJS6L3ZJ4xtXF7uNSHu7fbvsfF8t0mNNrrECsCPMIfk3qhtrGlt7inMQPLkb9VgXhI+Cvrw+wzviDcXeMNrnieXNdCh8/piUryw5TX33BYpppj3ltub7+7+aK/w5fbKjjkIWkNUtEebhSBteO3N9NqgX7kEMnTwP5OI6Z0fYTv8iydqpsFGl8SAmfTBzc7d5Tor7jCmfwTktgVX0IpHRpJ8Mnyqo59uCWX2nlCBgwR+TXANYMHPXcc7COSlbYHaNG9HFPJoyhdM6UANlUEqOtEDac8/X73e1SwNGwXxGi4QSi37IOE2j7P7bPQKDvN5iWig1HOnyZjeEtYWZ1uCvuJh6CMaXb0wL6J4gOvWFIbuSMhVg+59crRFRjLdTPeGX0rWfj1D9N2Lzp7U5dmF72JNHpDJ9hRFcjegMTThS2N6OoVINmLdBZasxf4ue9e+RmCcFCIpSy+S5GWQn0YbCO2yZRxvetuA2f6M4xE=
      app:
        master: metilda
      on:
        repo: metilda-uw/metilda