jobs:
  include:
  - stage: test backend
    language: python
    python:
    - 2.7.15
    install:
    - pip install -r requirements.txt
    script:
    - bash runTests.sh --python
  - stage: test frontend
    language: node_js
    node_js:
    - 8.12.0
    install:
    - "(cd frontend && npm ci)"
    script:
    - bash runTests.sh --nodejs
  - stage: deploy
    script: skip
    deploy: &heroku
      provider: heroku
      api_key:
        secure: RjhFKg6HLbM+WaZYUXN/e+lJQOYiECYCnxVkqxOzUhpLeOfCgBXMROQR2owzHLfVS3XYdg4pqVRscEFyQSwnpo32s81jt5lpN8PXA+iHKrQNQnvPkeui3kSRB8BpCp+oHraHHg/56/tPOrsw0yL+SnfKkvj/uaRP6ET1dVXgIFJmsF6fy3BVhM09nPg6KS8Bktx4aaTcAp6fUChGdpQ9BVLkxHr7grW6dW+pz9n5DAIXcW+P76wqRwjtA9XQr5IP+TaXF/HQwUcBcrnDm3YlvE2me25I0w/EaOp4ewgXBXGiVMN7sLB5pjbgxpCSLjMuckPkU8TOF2/AbEPDEuKKjVh3GmCvAaPkyb1rDjeJ2BCn05oKamLgIjqO9kuQdBywD/0FBDXguTjWgvJjxvzE2ryw86uFnHeYzzVe6LP9oosWAizRMZH5hXryEb479APMiwWYBbh60OCGw+zg6depMh7EgBK599bYLe38yA++8+i9gGAZSOB8A+sSyqhUtewABuShPz729rSYxrfhEctS2cn/ado1BpPja+pkMVWtgXERQSk9o0zyXn/5Ig52MvguQYMCQDahfVEumBFy0NCQSdyi3kPwI+Y0TxpMUSDAOptu0BIa7gE2/UzDEr5YESow91du6NPXyTe74P/oVoWKAMCzo4J7bWRZicV+zRiGYS4=
      app:
        master: metilda-dev
      on:
        repo: mitchl2/metilda