language: python
python:
- '2.7.15'
install:
- pip install -r requirements.txt
script:
- "(cd src && python -m unittest discover ../tests)"
deploy:
  provider: heroku
  api_key:
    secure: K376Wl6pXFCEwknycyA8I5ZXUkh1PrVMmkp6D0aXK0o/wrUgNcUoc1V/KSVbb/Xrp2ysP88nUxmuJcHioio5J1soAwOy3Wvqf9zAChGsmWu7vfg4fmQ0YORQaWzkVfUcpCqjs3qrFo4jDw9EGiuDog+hhuAzLBjfHi3qD5/e9x2krDqNYXwjpqFCl9XD9McjsWxePrlCbCcS/Z7bQ1ByxTulHAYyRW71voLat8qXPfl7mBZoGwkwYn3AHHUHTItUAXiEcG4yIYrA8UHbe44f5Pv7Dxo53v0DxWUEXZI5FywLINp2jeU+Uf0/akQgoUgOyDFVbgmFo+mQSonSE4gsHDNt33uz9b3tE6VZDIJ0KYZEqSq3r8aXc0cp7XgZBk/qPIz/IeicLpRRjuxuZPmvK8RSbp95q5y7mqUG1MmF7dYB2TGMNQZFgEUVngu+LVNKZbAqYkPxPxtTeiXs1puW6mcIcUpanknihU5cooHYbCx+elr2rh9XYvYUOCNIPdcgzugZpqySs+lY8HqubH15tOi5K0t80TJZsvO2U5l6KF5MCZ93CDGmJyZn/6ph7Av+okPiTbU8Ikxxke5QS0h4SIbb7V2+iUJ19IHAbH1WpLLLLctTtIt28At2zKtUY08ctCl3FjiJqk3/5kHxYlf5KffEnp7FARmrxyZO6rZ7GDA=
  app:
    master: metilda-dev
