language: python
python:
- 2.7.15
install:
- pip install -r requirements.txt
script:
- "(cd src && python -m unittest discover ../tests)"
deploy:
  provider: heroku
  api_key:
    secure: R+DpWOe5EbvHabp+Ci70IJWAQWrAUjMusf16nLAU3I5iVW5eUZhjXaUGcjX9RsjyIceUQ3vhaBb5qJnWlyfrubyYfmMDccy2wB33GaQxeyKd9q83ikWbBE/NUTjqdltXMxqftJ/0rqKOrdKK019sH8THUkKLRE38IieLohyF7TgFSafvARH3oHSDOahEgtXfIVNDX33Ueqxe5nMj0RYlotntkJy5TGLRS6XXiFu9RQ+ZR4UbgxLbPb5DSh5V3FjLeG0pPuxRRBjDmN0qBbACe6uGBZKil88VXZgREGC/8eQUCNlri6UqpFeOLiv7Hc6m0r/0SncW1bPGOvKezsJb3tYA/fBWUdOi2fx2lOpjDkC4/mNQcNKK1VD/st7SaPImfakHyh7JMB6bmfP9Bz7S8X1bUQrbDYZBO/RMk29r799LCl1u1AS52LMos8qeyF6IKH0A5CbkTCrTOAVrOF28bq9Uw6AUHpTjTSI6v5tXEmFzfNM6SVk1Xr//N7BUsZ7vI0dF65RKDS0BMG+dTnsYscsi8wUJe4zKDvOaUuuvpbMmjN5mt/ViCcBGatgGsh0aPu50eGqy8HeRzX5rTAhlVu/c8nV4K6Yv+i0Qxd+KU34ndnUKrpdahWENtjisqm+Un6cvs/SfQ1zEjUf/b57P/ewEoET8+yPC69sIwYfIcEs=
  app:
    master: metilda-dev
  on:
    repo: mitchl2/metilda
