language: python
python:
- 2.7.15
install:
- pip install -r requirements.txt
script:
- "(cd src && python -m unittest discover ../tests)"
deploy:
  provider: heroku
  app:
    master: metilda-dev
  api_key:
    secure: IYNjjOZT3M50Ke+1+sT/kyW+vrYKYZLwJRL0/0P/qIezgWaD+ipZwM3+5fZ8Vkp/f/aTFiilzfOk4E3rgq0wryfKUR05vyakQEQ83wXfz4a9WLYQKxTgTnGGsHx//CU5BM+bXHjVtli4CUhLaptLX+rpVsEc4vN03bmqAE91erMOetsBVaLn3n7LMHxzF+7zp/VZH+4Ts3TZrii+a+i8iEeh2Bg6KpaCTVssz15HPwaNuY6dvzJ6dtCOkJbQ0hxd9GMQCX8fQd5bQ5y9EQTSPfjG6hXY4W1b7p6cMucAAuPYIMUHrmUCInHz7hj+xMA5ESSRGcQ2M5+6pR0+TYtJPPmiutO6rJrC/aNDyfa1NcSa8WplJULe+chhsxGbgSXk09AJYs2O545Os/ivRSkgN5swueinDe+8uZWhz5FNDtZ19iVHbQRVfnJ4ncINXoCaIBRumKrrCqwdHDgXk2sJW1UGvUckEwM3tcu2i6JFryDeKSXNaVL4gubXjSr4qJfKcTG4hKT76YRrMHZPBK3Q6Zc0lqM18WzI5LUlUoQgygvgyKDFZniOTKobw4YCLoM8eaJyOybwFCvda9cj51NLMOJ26bkxdCiGbbR+3FJzguwqtwvZ9tWllxGXL+CxuC5OYKi+FDnQtmJxSfki7i6IaQMjSJKEneCNdtgf6ZS/cLg=
