language: python
python:
- 2.7.15
install:
- pip install -r requirements.txt
script:
- "(cd src && python -m unittest discover ../tests)"
deploy:
  provider: heroku
  api_key:
    secure: plVsT/FV19a0ipsnDnUtbWsCOY8IJrXmDEVZLIY6tNKgvz99VYLTuOXndeGOvUHIk+1wmWjdDrUWIsZ5zQ96NMgsp5ILkHEswx32jhwjye+Y9Lbbh8UKd7tBRBLjDRY4NeT878fUAuqIgar9T/a1waY3i684YYQYxq7h2skfV9fwFciCeti/5b4M0AiKwm75X8wpJHXQ38buq/2u2jD3ZQXpU/d5ZwcVl3Eunvh8jEltoVweNAAtMJd8SleqU5+pUMfNsutb1sNIbXkpaCGunpQnxsEl8ykZX5WWZVJnpr5eo1u3ioS335djVS9PrpfnlV/JJk3r8SajBknuEEae9fg+2eMjiwNbfkP48NbGHV7yx5J8ShS9WpDcgkeoOzcQT0aP5wYVF6lz5HQOElYvp1GTsSf0u8Lofbn4r7QENdaODQvfCMRdHNdfRrd57G/GTtaxMdHBHzpGeL7rCV0WVjd6EnWGivLj2Do9zdXGK3ADbx1ej7BAnmu1d1D00KUWItqMLMYHhwHpKr6XLGqvvs4QUuI5NQkjKziy7Qnh8HNUKxfIpzuZV69ECebVw14fDK6MWaLk/107gFDfhFdkBuEmMFKXfiC0+xK1tr3P1Q6BlIjuvo6OIZqMinhu9PmSSfdYKFltwM2coM86zFJS5+NEHGJ4ovOZN/UuwYS4j9Y=
  app:
    master: metilda-dev
  on:
    repo: mitchl2/metilda
