jobs:
  include:
  - stage: test backend
    language: python
    python:
    - 2.7.15
    install:
    - pip install -r requirements.txt
    script:
    - bash ./bin/runTests.sh --python
  - stage: test frontend
    language: node_js
    node_js:
    - 8.12.0
    install:
    - "(cd frontend && npm ci)"
    script:
    - bash ./bin/runTests.sh --nodejs-coverage
  - stage: deploy
    script: skip
    deploy: &heroku
      provider: heroku
      api_key:
        secure: cf9SmylEsetrzID1khWjy0v4euxKUspK+tfVWIoc43DEJkd9YGCDx7Qt/UkKJH9wWTe7YeC1FsasUrWsgqYsLYjOfYfoRgkpekQ7sr/V5ImaVmP4ItH7B5UTOAJLi1Eqr8W3f/IQ10zsX3afzIeEnoCo4PluG1OMvAo+9ZVeIH3X5xjPpPU7793/wr2ffFdcvUQ0C9T8REjyDFLSIRQDdMiyIuQUbPOE2RNNYs4Cq3rptyIreObOXViRWtnaondCg5an2Cwww4lY0aAwGUM6ACZOkOVufAJ+LtyPI1N8ZJPZVjo9xhWHWnJifDd0WQgfJ70xXBjcy5ky9O2ay0penTSSMPtJ40nqz8ZeObsvfS73Epj9Zu6j0IeAtRWlG6FRgXC/BgWADnb15TBDqiFjjwUEmy/DbSaiSKfUHGS7AZnunc/NTrEbclBud+yF1u9XmNQqyaokHqEzgQhOT4RPjjClqDul5TEOhcZ7vA4P5Dde7Ehzfp3GBNFs1nBaYnHh90A4u8viVQvpBEQqzoJOIBjrjHawO3MROsdSyK710vF+xASMbmjvb8MqCeA/dKIlCHc2aUJBWbO3CJieNiFnkCUFSq/Ki3payjvfJ6TzB/bY7L/tyH1Eftf43jO/iLJbF1KpXuc3CEsqfm4RGl+FDxsmhiz6s9kIMsnRMg0bnL0=
      app:
        master: metilda
      on:
        repo: metilda-uw/metilda