language: python
python:
- 2.7.15
install:
- pip install -r requirements.txt
script:
- "(cd src && python -m unittest discover ../tests)"
deploy:
  provider: heroku
  app:
    master: metilda-dev
  api_key:
    secure: PG/B6AiRPUr2/G3qB3oYR5qhLmoQaExhplfvUU6I9bRcb+sJbm5mLtl3VYpERocOrq8aeE/WpDfljdAXOnWItN6iPOLk9bTy7WsuY7sBn8FdF09h78kxpWrHoxH13vmRKjOhnOLur9FDl463J0w+lCY/a4CJlDnoNyt0Ub+CgZyzZYID5VcWdBsIM85sctvkTZJKLkzBpa3Vz2OchwcU35GDpSbwYMGqQcQ4jgF1x6UHuxa0fikWzzTcR098wfaHV/mK21z57sNWvfEos+/jimziuByPwhnaIsV9E3RAGhZ2QHqjRJCLnoet4Rty48eq+ET6gGmNTM6KFcMRdvcYRzpWcF8bf8WLmnKJFxKrnbV1MLhAuaU37K3tLMdMRTH4YItiS4hWNSVw1xctFXSL20RUmRsQi830Bcwuw8UKxHxCtoaxk+ww3kJV25rT4OnSHRss8moYo69KW08rMAydmoQOrH8jYHt+vjYgldpQ06Oh+WuA/SBmyFwpT4T3Ih/FvBa7qoCOb3VgX25E6iutSqFvAS1iylrDscoBNDeaW7Z/eM+0GU+Sgb+Oh8xkCOW3ABbYpiQkHvQEa3vvc6DouvvitrMFjDB5tuwgagusxng1E3++J4KyMiyzH1gYAvq2AbbtjNEUvvbPHXYOKH/7prH23BLO7Dn+4AvwyOSvd5A=
